//! Read-only Markdown export (Obsidian-readable) and a full JSON snapshot.

use crate::model::Node;
use crate::store::Store;
use anyhow::Result;
use chrono::NaiveDate;
use serde_json::json;
use std::fs;
use std::path::Path;

const HEADER: &str = "<!-- generated by thc; edits here are overwritten. Use `thc` or drop files into drop/. -->\n\n";

pub fn slug(s: &str) -> String {
    let mut out = String::new();
    let mut dash = false;
    for c in s.to_lowercase().chars() {
        if c.is_alphanumeric() {
            out.push(c);
            dash = false;
        } else if !dash && !out.is_empty() {
            out.push('-');
            dash = true;
        }
    }
    let out = out.trim_end_matches('-').to_string();
    if out.is_empty() { "untitled".into() } else { out }
}

fn task_line(store: &Store, n: &Node) -> String {
    let cb = match n.status.as_deref() {
        Some("done") => "- [x] ",
        Some("cancelled") => "- [-] ",
        Some("doing") => "- [/] ",
        Some(_) => "- [ ] ",
        None => "- ",
    };
    let mut s = format!("{cb}{}", store.render_text(&n.text).replace('\n', " "));
    if let Some(p) = &n.priority {
        s.push_str(match p.as_str() {
            "high" => " ⏫",
            "med" => " 🔼",
            _ => " 🔽",
        });
    }
    if let Some(r) = n.repeat.as_ref().and_then(|r| r.get("text")).and_then(|t| t.as_str()) {
        s.push_str(&format!(" 🔁 {r}"));
    }
    if let Some(d) = &n.scheduled {
        s.push_str(&format!(" ⏳ {}", d.replace('T', " ")));
    }
    if let Some(d) = &n.due {
        s.push_str(&format!(" 📅 {}", d.replace('T', " ")));
    }
    if let Some(d) = &n.done_at {
        if n.status.as_deref() == Some("done") {
            s.push_str(&format!(" ✅ {}", &d[..10.min(d.len())]));
        }
    }
    s.push_str(&format!(" ^{}", n.id));
    s
}

fn outline(store: &Store, parent: &str, depth: usize, out: &mut String) -> Result<()> {
    let mut prev_para: Option<bool> = None;
    for c in store.children(parent)? {
        // A blank line before a top-level note where it has one (`gap`, writing.md §1): its own
        // when set, else the default (a paragraph keeps a blank line on either side).
        if depth == 0 {
            let para = crate::edit::has_para_style(store, &c.id) && c.status.is_none();
            if let Some(p) = prev_para {
                if crate::edit::gap_of(store, &c.id).unwrap_or(p || para) {
                    out.push('\n');
                }
            }
            prev_para = Some(para);
        }
        let line = task_line(store, &c);
        out.push_str(&"    ".repeat(depth));
        out.push_str(&line);
        out.push('\n');
        outline(store, &c.id, depth + 1, out)?;
    }
    Ok(())
}

pub struct ExportStats {
    pub pages: usize,
    pub journals: usize,
}

pub fn markdown(store: &Store, dir: &Path, today: NaiveDate) -> Result<ExportStats> {
    let tmp = dir.with_extension("tmp");
    if tmp.exists() {
        fs::remove_dir_all(&tmp)?;
    }
    fs::create_dir_all(tmp.join("pages"))?;
    fs::create_dir_all(tmp.join("journal"))?;
    let mut stats = ExportStats { pages: 0, journals: 0 };

    let roots = store.nodes_where("n.parent IS NULL AND n.deleted=0 AND n.is_tag=0 ORDER BY n.ord", &[])?;
    let mut inbox = String::from(HEADER);
    inbox.push_str("# Inbox\n\n");
    for r in &roots {
        if let Some(j) = &r.journal {
            let mut s = String::from(HEADER);
            s.push_str(&format!("# {j}\n\n"));
            outline(store, &r.id, 0, &mut s)?;
            fs::write(tmp.join("journal").join(format!("{j}.md")), s)?;
            stats.journals += 1;
        } else if let Some(t) = &r.title {
            // Frontmatter must be first for Obsidian to read it.
            let tags = store.tags_of(&r.id)?;
            let mut s = format!("---\ntags: [{}]\nthc_id: {}\n---\n", tags.join(", "), r.id);
            s.push_str(HEADER);
            s.push_str(&format!("# {t}\n\n"));
            if !r.text.is_empty() {
                s.push_str(&store.render_text(&r.text));
                s.push_str("\n\n");
            }
            outline(store, &r.id, 0, &mut s)?;
            let mut name = slug(t);
            if tmp.join("pages").join(format!("{name}.md")).exists() {
                name = format!("{name}-{}", &r.id[..5]);
            }
            fs::write(tmp.join("pages").join(format!("{name}.md")), s)?;
            stats.pages += 1;
        } else {
            inbox.push_str(&task_line(store, r));
            inbox.push('\n');
            outline(store, &r.id, 1, &mut inbox)?;
        }
    }
    fs::write(tmp.join("inbox.md"), inbox)?;

    let mut agenda = String::from(HEADER);
    let t = today.format("%Y-%m-%d").to_string();
    agenda.push_str(&format!("# Agenda ({t})\n\n## Overdue\n\n"));
    for n in store.query("status:open (due<today or sched<today) sort:date", today, 500)? {
        agenda.push_str(&task_line(store, &n));
        agenda.push('\n');
    }
    agenda.push_str("\n## Today\n\n");
    for n in store.query("status:open (due=today or sched=today) sort:date", today, 500)? {
        agenda.push_str(&task_line(store, &n));
        agenda.push('\n');
    }
    agenda.push_str("\n## Next 7 days\n\n");
    for n in store.query("(due>today and due<=+7d) or (sched>today and sched<=+7d) -status:closed sort:date", today, 500)? {
        agenda.push_str(&task_line(store, &n));
        agenda.push('\n');
    }
    fs::write(tmp.join("agenda.md"), agenda)?;

    if dir.exists() {
        fs::remove_dir_all(dir)?;
    }
    fs::rename(&tmp, dir)?;
    Ok(stats)
}

pub fn json_snapshot(store: &Store) -> Result<serde_json::Value> {
    let nodes = store.nodes_where("n.deleted=0 ORDER BY n.parent, n.ord", &[])?;
    let mut out = Vec::with_capacity(nodes.len());
    for n in nodes {
        let mut v = serde_json::to_value(&n)?;
        v["tags"] = json!(store.tags_of(&n.id)?);
        v["props"] = json!(store.props_of(&n.id)?);
        v["alerts"] = json!(store.alerts_of(&n.id)?);
        out.push(v);
    }
    Ok(json!({ "format": crate::event::FORMAT_VERSION, "nodes": out }))
}
