//! `thc setup claude|codex`: install or refresh a repo's agent files from the binary (agents.md §2.3).
//! Machine setup (`thc setup`, `--user`, `--status`, `--undo`) is in bootstrap.rs (setup.md).
//! Writes only `.claude/skills/thc/SKILL.md`, the marked block in AGENTS.md, and (with `--hook`)
//! a SessionStart hook in `.claude/settings.json`. Never touches the vault.

use crate::out::Out;
use anyhow::{Result, anyhow};
use serde_json::{Value, json};
use std::path::{Path, PathBuf};

const VERSION: &str = env!("CARGO_PKG_VERSION");
const BEGIN: &str = "<!-- thc:begin";
const END: &str = "<!-- thc:end -->";

pub fn skill_text() -> String {
    format!(
        "---\nname: thc\ndescription: >-\n  Manage the user's notes, todos, journal, dates and reminders with the `thc` CLI (thought-central). Use when the user asks to capture a thought, add/complete/reschedule a todo, set a reminder, look at today/agenda/journal, search or query their notes, or review what an agent changed. Also use when the user asks to coordinate work or agents through thc (\"coordinate with thc\", \"use thc as the task board\", \"pick the next task\", \"claim a task\"): see `thc instructions coordination`.\n---\n<!-- thc v{VERSION} · generated by `thc setup claude`; edits are overwritten -->\n\n# Using thc\n\n`thc` is the user's CLI-first notes and todo system. The CLI is the API.\n\n1. Start with `thc prime`: current state plus the rules, in about 15 lines.\n2. Before any write, set `THC_ACTOR` to your actual agent name (e.g. `export THC_ACTOR=codex` or `export THC_ACTOR=claude`), never another model's name. Use a stable role suffix if needed (e.g. `codex-reviewer`); record an available session/thread ID separately as a `session_id` property on notes/tasks, with `agent_role` when useful. Never invent an ID or store credentials.\n3. Read with `--json` (or `--fields id,short,due`). Refer to nodes by `id` or a 4+ char prefix.\n4. Writes: `thc add \"text due:fri #tag !high\"` (today's journal), `thc todo`, `thc remind --at`,\n   `thc done <id>`, `thc set <id> k=v`, `thc mv <id> --under <id>`. Use `--key <k>` so retries are no-ops.\n5. Conflicts are the human's call: mention them, never resolve unless asked; `thc text` exits 4 on them.\n6. Never edit vault files directly.\n\nMore: `thc instructions <topic>` (capture, query, dates, conflicts, exit-codes, json, commands, coordination, roles, messages, team),\n`thc schema <cmd>` for JSON Schemas.\n\n{}\n{}\n{}",
        crate::instructions::COORDINATION, crate::instructions::MESSAGES, crate::instructions::TEAM
    )
}

pub fn agents_block() -> String {
    format!("{BEGIN} v{VERSION} -->\n## Part 1: Using `thc` as an agent\n\n{}{END}", crate::instructions::all())
}

fn stamped_version(text: &str, marker: &str) -> Option<String> {
    let i = text.find(marker)? + marker.len();
    let rest = text[i..].trim_start();
    let v = rest.strip_prefix('v')?;
    Some(v.chars().take_while(|c| c.is_ascii_digit() || *c == '.').collect())
}

/// Replace the marked block (or append one) and return the new file text.
fn merge_agents(existing: &str) -> String {
    merge_block(existing, &agents_block())
}

/// Put `block` (a `<!-- thc:begin … -->`…`<!-- thc:end -->` block) in place of the marked block,
/// or append it, keeping everything else in the file as it was.
pub fn merge_block(existing: &str, block: &str) -> String {
    match (existing.find(BEGIN), existing.find(END)) {
        (Some(a), Some(b)) if b > a => format!("{}{}{}", &existing[..a], block, &existing[b + END.len()..]),
        _ => {
            let sep = if existing.is_empty() || existing.ends_with("\n\n") { "" } else if existing.ends_with('\n') { "\n" } else { "\n\n" };
            format!("{existing}{sep}{block}\n")
        }
    }
}

/// The file without thc's marked block (and the blank line before it, if setup added one).
pub fn strip_block(existing: &str) -> String {
    match (existing.find(BEGIN), existing.find(END)) {
        (Some(a), Some(b)) if b > a => {
            let head = existing[..a].trim_end_matches('\n');
            let tail = existing[b + END.len()..].trim_start_matches('\n');
            match (head.is_empty(), tail.is_empty()) {
                (true, _) => tail.to_string(),
                (false, true) => format!("{head}\n"),
                (false, false) => format!("{head}\n\n{tail}"),
            }
        }
        _ => existing.to_string(),
    }
}

/// The short block for an agent's user-level instructions (`~/.codex/AGENTS.md`, setup.md §1):
/// read in every session, so it's the skill's few lines, not the whole of Part 1.
pub fn user_block() -> String {
    let skill = skill_text();
    let body = skill.split("# Using thc").nth(1).unwrap_or("");
    format!("{BEGIN} v{VERSION} · generated by `thc setup codex --user`; edits are overwritten -->\n## Using thc{}{END}", body.trim_end().to_string() + "\n")
}

struct Change {
    verb: &'static str,
    path: PathBuf,
    note: String,
    content: String,
    stale_msg: Option<String>,
}

fn plan(dir: &Path, agent: &str, hook: bool) -> Result<Vec<Change>> {
    let mut changes = Vec::new();
    if agent == "claude" {
        let p = dir.join(".claude/skills/thc/SKILL.md");
        let want = skill_text();
        let have = std::fs::read_to_string(&p).ok();
        let lines = want.lines().count();
        match &have {
            None => changes.push(Change { verb: "write", path: p, note: format!("new · {lines} lines"), content: want, stale_msg: Some("SKILL.md is missing · thc setup claude to install".into()) }),
            Some(h) if *h != want => {
                let (note, msg) = match stamped_version(h, "<!-- thc") {
                    Some(v) => (format!("from thc {v}"), format!("SKILL.md is from thc {v} · thc setup claude to refresh")),
                    None => ("hand-written · replaced".to_string(), "SKILL.md wasn't written by thc setup · thc setup claude to refresh".to_string()),
                };
                changes.push(Change { verb: "update", path: p, note, content: want, stale_msg: Some(msg) });
            }
            _ => {}
        }
    }
    let p = dir.join("AGENTS.md");
    let have = std::fs::read_to_string(&p).unwrap_or_default();
    let want = merge_agents(&have);
    if want != have {
        let from = stamped_version(&have, BEGIN);
        let note = match &from {
            Some(v) => format!("block {BEGIN}/end --> · from thc {v}"),
            None => "block <!-- thc:begin/end --> · added".to_string(),
        };
        let stale = Some(match from {
            Some(v) => format!("AGENTS.md block is from thc {v} · thc setup {agent} to refresh"),
            None => format!("AGENTS.md has no thc block · thc setup {agent} to add it"),
        });
        changes.push(Change { verb: if have.is_empty() { "write" } else { "update" }, path: p, note, content: want, stale_msg: stale });
    }
    if hook && agent == "claude" {
        let p = dir.join(".claude/settings.json");
        let mut v: Value = std::fs::read_to_string(&p).ok().and_then(|s| serde_json::from_str(&s).ok()).unwrap_or_else(|| json!({}));
        let has = v["hooks"]["SessionStart"].as_array().is_some_and(|a| a.iter().any(|h| h.to_string().contains("thc prime")));
        if !has {
            let entry = json!({ "hooks": [{ "type": "command", "command": "thc prime" }] });
            match v["hooks"]["SessionStart"].as_array_mut() {
                Some(a) => a.push(entry),
                None => {
                    if !v["hooks"].is_object() {
                        v["hooks"] = json!({});
                    }
                    v["hooks"]["SessionStart"] = json!([entry]);
                }
            }
            changes.push(Change { verb: "hook", path: p, note: "SessionStart → thc prime".into(), content: serde_json::to_string_pretty(&v)? + "\n", stale_msg: None });
        }
    }
    Ok(changes)
}

/// Staleness lines for `thc prime` (empty when up to date or not installed here).
pub fn stale_lines(dir: &Path) -> Vec<String> {
    let skill = dir.join(".claude/skills/thc/SKILL.md");
    if !skill.exists() {
        return vec![];
    }
    plan(dir, "claude", false).map(|c| c.into_iter().filter_map(|c| c.stale_msg).collect()).unwrap_or_default()
}

pub fn run(out: &mut Out, agent: &str, dry_run: bool, check: bool, hook: bool, implicit_dry: bool) -> Result<()> {
    if agent != "claude" && agent != "codex" {
        return Err(thc_core::error::usage("setup supports claude or codex"));
    }
    let dir = std::env::current_dir()?;
    let changes = plan(&dir, agent, hook)?;
    if check {
        let stale: Vec<String> = changes.iter().filter_map(|c| c.stale_msg.clone()).collect();
        if out.json {
            out.json(&json!({ "stale": !stale.is_empty(), "messages": stale }));
        } else if stale.is_empty() {
            out.line(format!("thc agent files are current (thc {VERSION})"));
        } else {
            for s in &stale {
                out.line(s);
            }
        }
        out.flush();
        return if stale.is_empty() { Ok(()) } else { Err(anyhow!(crate::daemon_cmd::Quiet)) };
    }
    let rel = |p: &Path| p.strip_prefix(&dir).map(|r| r.display().to_string()).unwrap_or_else(|_| p.display().to_string());
    if out.json {
        out.json(&json!({ "dry_run": dry_run, "changes": changes.iter().map(|c| json!({ "action": c.verb, "path": rel(&c.path), "note": c.note })).collect::<Vec<_>>() }));
    } else {
        out.line(format!("setup {agent}{}", if dry_run { " (dry run)" } else { "" }));
        if changes.is_empty() {
            out.line(format!("  everything is current (thc {VERSION})"));
        }
        for c in &changes {
            let verb = if dry_run {
                c.verb
            } else {
                match c.verb {
                    "write" => "wrote",
                    "update" => "updated",
                    "hook" => "hooked",
                    v => v,
                }
            };
            out.line(format!("  {:<7} {:<32} {}", verb, rel(&c.path), out.dim(&c.note)));
        }
        if !hook && agent == "claude" && !dir.join(".claude/settings.json").exists() {
            out.line(out.dim("  hook    .claude/settings.json           SessionStart → thc prime   (add with --hook)"));
        }
        if dry_run && !changes.is_empty() {
            if implicit_dry {
                out.line(out.dim("stdin isn't a terminal, so nothing was written · add --yes to apply"));
            } else {
                out.line(out.dim("run without --dry-run to apply"));
            }
        } else if !dry_run && !changes.is_empty() {
            out.line(out.dim(&format!("done · thc setup {agent} --check to verify later")));
        }
    }
    if !dry_run {
        for c in &changes {
            if let Some(parent) = c.path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&c.path, &c.content)?;
        }
    }
    Ok(())
}
