//! The UI as data. A `Ui` is everything on screen: a tree of nodes, the data sources the tree
//! binds to, and the keys. It is plain JSON, so a whole UI can be written by hand, generated by
//! an agent, pushed into a running screen and read back out.
//!
//! The world (your notes, prices, logs) is not in here. A node names a source (`bind`), a source
//! says how to fetch the world (a command that prints JSON, or a literal value), and the view
//! reads whatever the runtime last fetched.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::BTreeMap;

/// One whole UI.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Ui {
    pub root: Node,
    /// Named data sources, fetched by the runtime and bound to by nodes.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub data: BTreeMap<String, Source>,
    /// Keys that work everywhere (a focused node's own `keys` win).
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub keys: BTreeMap<String, Action>,
}

/// A node: what it is (`type` and its fields) plus the parts every node shares.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Node {
    /// Stable identity. A node with an id keeps its selection and scroll across pushes, can be
    /// focused (lists, tables) and can be replaced alone (`patch`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Its share of the parent row/col: `12` (cells), `"30%"`, `"*"` (the default) or `"2*"`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<Size>,
    /// A title draws a border with it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub border: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<Style>,
    /// The data source this node reads (a key of `Ui::data`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bind: Option<String>,
    /// Keys that work while this node has focus.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub keys: BTreeMap<String, Action>,
    #[serde(flatten)]
    pub kind: Kind,
}

impl Default for Node {
    fn default() -> Self {
        Node {
            id: None,
            size: None,
            title: None,
            border: false,
            style: None,
            bind: None,
            keys: BTreeMap::new(),
            kind: Kind::Text { text: String::new() },
        }
    }
}

/// The closed set of components. Layouts arrange these; they don't add new ones.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum Kind {
    /// Children stacked top to bottom.
    Col { children: Vec<Node> },
    /// Children side by side.
    Row { children: Vec<Node> },
    /// Text. `{field}` placeholders fill from the bound value (`{a.b}` reaches in).
    Text { text: String },
    /// A selectable list of `items`, or of the bound array. `item` formats each one.
    List {
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        items: Vec<Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        item: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        empty: Option<String>,
    },
    /// A selectable table over the bound array (or `items`).
    Table {
        columns: Vec<Column>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        items: Vec<Value>,
    },
    /// A sparkline over numbers: `values`, or `field` of each bound item.
    Sparkline {
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        values: Vec<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        field: Option<String>,
    },
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Column {
    pub title: String,
    /// A template over the row, e.g. `"{text}"` or `"{due} {priority}"`.
    pub value: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<Size>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Size {
    Cells(u16),
    Spec(String),
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Style {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fg: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bg: Option<String>,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub bold: bool,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub dim: bool,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub italic: bool,
}

/// Where a source's value comes from. A command prints JSON on stdout; `path` picks a part of it
/// (`"items"`); `every` re-runs it (seconds).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Source {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cmd: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shell: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub every: Option<f64>,
}

/// What a key does. Names: `quit`, `up`, `down`, `top`, `bottom`, `focus_next`, `focus_prev`,
/// `refresh`. `run` executes a command (templated against the selected item, `{id}`), then
/// refreshes; `load` replaces the whole UI with a file's.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Action {
    Named(String),
    Run { run: Vec<String> },
    Load { load: String },
    Focus { focus: String },
}

impl Node {
    pub fn children(&self) -> &[Node] {
        match &self.kind {
            Kind::Col { children } | Kind::Row { children } => children,
            _ => &[],
        }
    }

    pub fn children_mut(&mut self) -> Option<&mut Vec<Node>> {
        match &mut self.kind {
            Kind::Col { children } | Kind::Row { children } => Some(children),
            _ => None,
        }
    }

    /// Lists and tables with an id take focus.
    pub fn focusable(&self) -> bool {
        self.id.is_some() && matches!(self.kind, Kind::List { .. } | Kind::Table { .. })
    }

    pub fn walk<'a>(&'a self, out: &mut Vec<&'a Node>) {
        out.push(self);
        for c in self.children() {
            c.walk(out);
        }
    }

    pub fn find(&self, id: &str) -> Option<&Node> {
        let mut all = Vec::new();
        self.walk(&mut all);
        all.into_iter().find(|n| n.id.as_deref() == Some(id))
    }

    /// Replace the node with this id; false when there is none.
    pub fn replace(&mut self, id: &str, with: &Node) -> bool {
        if self.id.as_deref() == Some(id) {
            *self = with.clone();
            return true;
        }
        self.children_mut().is_some_and(|cs| cs.iter_mut().any(|c| c.replace(id, with)))
    }
}

/// `{field}` and `{a.b}` filled from `v`; a missing field is empty. A plain string value fills
/// `{.}`. `{{` is a literal brace.
pub fn fill(template: &str, v: &Value) -> String {
    let mut out = String::new();
    let mut rest = template;
    while let Some(i) = rest.find('{') {
        out.push_str(&rest[..i]);
        if rest[i..].starts_with("{{") {
            out.push('{');
            rest = &rest[i + 2..];
            continue;
        }
        match rest[i..].find('}') {
            Some(j) => {
                out.push_str(&scalar(lookup(v, &rest[i + 1..i + j])));
                rest = &rest[i + j + 1..];
            }
            None => {
                out.push_str(&rest[i..]);
                rest = "";
            }
        }
    }
    out.push_str(rest);
    out
}

/// A dotted path into a value (`items`, `a.b`, `rows.0`); `.` or empty is the value itself.
pub fn lookup<'a>(v: &'a Value, path: &str) -> Option<&'a Value> {
    if path.is_empty() || path == "." {
        return Some(v);
    }
    path.split('.').try_fold(v, |v, k| match v {
        Value::Object(m) => m.get(k),
        Value::Array(a) => k.parse::<usize>().ok().and_then(|i| a.get(i)),
        _ => None,
    })
}

pub fn scalar(v: Option<&Value>) -> String {
    match v {
        None | Some(Value::Null) => String::new(),
        Some(Value::String(s)) => s.clone(),
        Some(Value::Array(a)) => a.iter().map(|x| scalar(Some(x))).collect::<Vec<_>>().join(", "),
        Some(other) => other.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn fill_reads_fields_and_paths() {
        let v = json!({"text": "Buy milk", "due": "2026-10-09", "a": {"b": 3}, "tags": ["x", "y"]});
        assert_eq!(fill("{text} · {due} · {a.b} · {tags} · {nope}", &v), "Buy milk · 2026-10-09 · 3 · x, y · ");
        assert_eq!(fill("{.}", &json!("plain")), "plain");
        assert_eq!(fill("{{literal}", &v), "{literal}");
    }

    #[test]
    fn a_ui_round_trips_through_json() {
        let ui: Ui = serde_json::from_value(json!({
            "root": {"type": "col", "children": [
                {"type": "text", "text": "hi", "size": 1},
                {"type": "list", "id": "l", "title": "Tasks", "bind": "tasks", "item": "{text}",
                 "keys": {"x": {"run": ["thc", "done", "{id}"]}}}
            ]},
            "data": {"tasks": {"cmd": ["thc", "q", "status:open", "--json"], "path": "items"}},
            "keys": {"q": "quit"}
        }))
        .unwrap();
        let back: Ui = serde_json::from_value(serde_json::to_value(&ui).unwrap()).unwrap();
        assert_eq!(ui, back);
        assert!(ui.root.find("l").unwrap().focusable());
    }
}
