//! The UI as data. A `Ui` is everything on screen: a tree of nodes, the data sources the tree
//! binds to, and the keys. It is plain JSON, so a whole UI can be written by hand, generated by
//! an agent, pushed into a running screen and read back out.
//!
//! The world (your notes, prices, logs) is not in here. A node names a source (`bind`), a source
//! says how to fetch the world (a command that prints JSON, or a literal value), and the view
//! reads whatever the runtime last fetched.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::BTreeMap;

/// One whole UI.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Ui {
    pub root: Node,
    /// Named data sources, fetched by the runtime and bound to by nodes.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub data: BTreeMap<String, Source>,
    /// Keys that work everywhere (a focused node's own `keys` win).
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub keys: BTreeMap<String, Action>,
    /// Named colours every node can use, and the screen's own (`bg`, `fg`, `border`, `accent`,
    /// `pos`, `neg`, `hover`).
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub theme: BTreeMap<String, String>,
    /// Callouts, arrows, rings and spotlights over the screen, anchored to nodes and rows
    /// (placed by caretline-layers).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub layers: Vec<LayerSpec>,
    /// `false` hides the runtime's own status line (hints and the fps meter), so the UI owns every
    /// row. The meter is still bindable as `$stats`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_bar: Option<bool>,
}

/// One layer, anchored to a node (`on`) or one of its rows (`row`).
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct LayerSpec {
    pub on: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub row: Option<usize>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Fill `title` and `text` from this source (`"fin.kpi"`), so a callout shows live values.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bind: Option<String>,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub arrow: bool,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub ring: bool,
    /// The ring pulses with this period (ms).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pulse: Option<u32>,
    /// Dim everything but the anchor and the box.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub spotlight: bool,
    /// Sides to try, in order: `below`, `above`, `right`, `left`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub place: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub width: Option<u16>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub look: Option<Look>,
    /// Who placed it; drawn in the border (`◆ analyst`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub by: Option<String>,
}

/// How a layer looks: colours by name or `#rrggbb`, and the border.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Look {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub accent: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fill: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fg: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ring: Option<String>,
    /// `rounded` (default), `double`, `thick` or `plain`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub edge: Option<String>,
}

/// A node: what it is (`type` and its fields) plus the parts every node shares.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Node {
    /// Stable identity. A node with an id keeps its selection and scroll across pushes, can be
    /// focused (lists, tables) and can be replaced alone (`patch`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Its share of the parent row/col: `12` (cells), `"30%"`, `"*"` (the default) or `"2*"`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<Size>,
    /// A title draws a border with it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub border: bool,
    /// The border: `rounded` (default), `double`, `thick` or `plain`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub edge: Option<String>,
    /// `left` (default), `center` or `right`, for text and big numbers.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub align: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<Style>,
    /// A callout that follows the mouse over this node's rows, filled from the hovered row.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tip: Option<Tip>,
    /// What a click does (after focusing the node and selecting the clicked row).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub click: Option<Action>,
    /// A pixel panel behind the node (rounded, shadowed), where the terminal draws images; a plain
    /// border where it doesn't.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backdrop: Option<Backdrop>,
    /// Text drawn this many times larger (kitty's text sizing, OSC 66), where the terminal can.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<u8>,
    /// The data source this node reads (a key of `Ui::data`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bind: Option<String>,
    /// Keys that work while this node has focus.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub keys: BTreeMap<String, Action>,
    #[serde(flatten)]
    pub kind: Kind,
}

impl Default for Node {
    fn default() -> Self {
        Node {
            id: None,
            size: None,
            title: None,
            border: false,
            style: None,
            bind: None,
            keys: BTreeMap::new(),
            edge: None,
            align: None,
            tip: None,
            click: None,
            backdrop: None,
            scale: None,
            kind: Kind::Text { text: String::new() },
        }
    }
}

/// The closed set of components. Layouts arrange these; they don't add new ones.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum Kind {
    /// Children stacked top to bottom.
    Col { children: Vec<Node> },
    /// Children side by side.
    Row { children: Vec<Node> },
    /// Text. `{field}` placeholders fill from the bound value (`{a.b}` reaches in).
    Text { text: String },
    /// A selectable list of `items`, or of the bound array. `item` formats each one; with
    /// `variant` (a path), a row whose value there is a key of `variants` uses that template
    /// instead (a section header, a blank). Rows whose variant is in `skip` aren't selectable.
    /// `mark` and `lead` start the selected and the other rows (default `▸ ` and two spaces);
    /// `selected` styles the selected row (a style spec; default reverse when focused).
    List {
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        items: Vec<Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        item: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        empty: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        variant: Option<String>,
        #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
        variants: BTreeMap<String, String>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        skip: Vec<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        mark: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        lead: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        selected: Option<String>,
    },
    /// A line filling the node: `glyph` (default `│` when taller than wide, else `─`).
    Rule {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        glyph: Option<String>,
    },
    /// A selectable table over the bound array (or `items`).
    Table {
        columns: Vec<Column>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        items: Vec<Value>,
    },
    /// A sparkline over numbers: `values`, or `field` of each bound item.
    Sparkline {
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        values: Vec<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        field: Option<String>,
    },
    /// Lines over shared axes. Each series reads numbers from a bind (and `field` of each item).
    Chart {
        series: Vec<Series>,
        /// Labels spread along the x axis.
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        labels: Vec<String>,
    },
    /// Bars over the bound array (or `items`): `label` is a template, `value` a path. Negative
    /// values hang below a zero line.
    Bars {
        label: String,
        value: String,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        items: Vec<Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        width: Option<u16>,
    },
    /// A filled bar: `value` (a template giving a number) out of `max` (default 1).
    Gauge {
        value: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
    /// Large digits (a KPI): the filled template, in a 3-row block font.
    Big { text: String },
    /// One child at a time, picked by a row of tab titles (click one, or ←/→ when focused).
    Tabs { tabs: Vec<String>, children: Vec<Node> },
    /// Lines drawn in pixels (anti-aliased, a gradient under each) where the terminal draws
    /// images; a braille chart where it doesn't.
    Plot {
        series: Vec<Series>,
        #[serde(default = "yes")]
        fill: bool,
        /// Line width as a fraction of a cell's height.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        width: Option<f32>,
    },
    /// An image file (PNG), scaled into the node.
    Image { src: String },
    /// Vector art: inline SVG markup (`{field}` placeholders filled from the bound value, so it
    /// can draw live data) or an `.svg` file, rendered at the terminal's real pixel size. `alt`
    /// shows where the terminal has no graphics.
    Svg {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        svg: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        src: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        alt: Option<String>,
    },
    /// A lit, glowing dot (the brand mark's `•`): `color`, and `glow` (0 for none).
    Dot {
        color: String,
        #[serde(default)]
        glow: f32,
    },
    /// A world map with a point per bound item at `lat`/`lon` (paths), labelled by `label`.
    Map {
        lat: String,
        lon: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
}

fn yes() -> bool {
    true
}

/// A pixel panel: `fill` (and `fill2` for a vertical gradient), `border`, a corner `radius` and a
/// `shadow` (fractions of a cell's height), and `glow` (the shadow's colour, for a lit panel).
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Backdrop {
    pub fill: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fill2: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub border: Option<String>,
    #[serde(default = "radius")]
    pub radius: f32,
    #[serde(default)]
    pub shadow: f32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub glow: Option<String>,
}

fn radius() -> f32 {
    0.5
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Series {
    pub name: String,
    pub bind: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Tip {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    pub text: String,
}

/// A cell's background from its value: `min` is the `neg` colour, `max` the `pos` colour.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Heat {
    pub value: String,
    pub min: f64,
    pub max: f64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Column {
    pub title: String,
    /// A template over the row, e.g. `"{text}"` or `"{due} {priority}"`.
    pub value: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<Size>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub align: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub heat: Option<Heat>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Size {
    Cells(u16),
    Spec(String),
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Style {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fg: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bg: Option<String>,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub bold: bool,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub dim: bool,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub italic: bool,
}

/// Where a source's value comes from. A command prints JSON on stdout; `path` picks a part of it
/// (`"items"`); `every` re-runs it (seconds). A `stream` command keeps running and each JSON line
/// it prints replaces the value: a live feed without a process per update.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Source {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cmd: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shell: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stream: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub every: Option<f64>,
}

/// What a key does. Names: `quit`, `up`, `down`, `top`, `bottom`, `focus_next`, `focus_prev`,
/// `refresh`. `run` executes a command (templated against the selected item, `{id}`), then
/// refreshes; `load` replaces the whole UI with a file's.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Action {
    Named(String),
    Run { run: Vec<String> },
    Load { load: String },
    Focus { focus: String },
}

impl Node {
    /// Whether row `r` (`v`) can't be selected: its variant is in the list's `skip`.
    pub fn skips(&self, v: &Value) -> bool {
        match &self.kind {
            Kind::List { variant: Some(p), skip, .. } if !skip.is_empty() => skip.contains(&scalar(lookup(v, p))),
            _ => false,
        }
    }

    pub fn children(&self) -> &[Node] {
        match &self.kind {
            Kind::Col { children } | Kind::Row { children } | Kind::Tabs { children, .. } => children,
            _ => &[],
        }
    }

    pub fn children_mut(&mut self) -> Option<&mut Vec<Node>> {
        match &mut self.kind {
            Kind::Col { children } | Kind::Row { children } | Kind::Tabs { children, .. } => Some(children),
            _ => None,
        }
    }

    /// Lists, tables and tabs with an id take focus.
    pub fn focusable(&self) -> bool {
        self.id.is_some() && matches!(self.kind, Kind::List { .. } | Kind::Table { .. } | Kind::Tabs { .. })
    }

    /// Like `walk`, but only into the shown child of each tabs node (`tab` gives its index).
    pub fn walk_shown<'a>(&'a self, tab: &dyn Fn(&Node) -> usize, out: &mut Vec<&'a Node>) {
        out.push(self);
        match &self.kind {
            Kind::Tabs { children, .. } => {
                if let Some(c) = children.get(tab(self).min(children.len().saturating_sub(1))) {
                    c.walk_shown(tab, out);
                }
            }
            _ => {
                for c in self.children() {
                    c.walk_shown(tab, out);
                }
            }
        }
    }

    pub fn walk<'a>(&'a self, out: &mut Vec<&'a Node>) {
        out.push(self);
        for c in self.children() {
            c.walk(out);
        }
    }

    pub fn find(&self, id: &str) -> Option<&Node> {
        let mut all = Vec::new();
        self.walk(&mut all);
        all.into_iter().find(|n| n.id.as_deref() == Some(id))
    }

    /// Replace the node with this id; false when there is none.
    pub fn replace(&mut self, id: &str, with: &Node) -> bool {
        if self.id.as_deref() == Some(id) {
            *self = with.clone();
            return true;
        }
        self.children_mut().is_some_and(|cs| cs.iter_mut().any(|c| c.replace(id, with)))
    }
}

/// One run of a filled template: text, its style (a spec like `accent+b`, from `<accent+b>`), the
/// sign of a `{±x}` number, a tab (the rest of the line is right-aligned) or a fill character
/// (`{*─}`: repeat to the end of the line).
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Seg {
    pub text: String,
    pub style: Option<String>,
    pub sign: Option<bool>,
    pub tab: bool,
    pub fill: Option<char>,
}

/// A template filled from `v`, as styled runs. The language:
///
/// - `{path}` a value (`{a.b}`, `{rows.0}`; `{.}` the value itself); `{{` is a literal brace.
/// - `{±path}` a value marked with its number's sign, for the view to colour.
/// - `{path|a=x;b=y;*=z}` maps the value (`*` is anything else); the result may carry styles and
///   `$` stands for the value. `{path|?then}` is `then` when the value isn't empty, `{path|!else}`
///   when it is. `{path|markup}` reads the value's own `<style>` runs (values are plain text
///   otherwise, so data can't restyle the screen).
/// - `<spec>` … `</>` a style: theme tokens or colours, `on-<colour>` for the background, and
///   `b` `d` `i` `u` `r` `s` (bold, dim, italic, underline, reverse, strike), joined by `+`.
///   Inside a mapped or `|markup` value a style layers on the one around it (a `<tag>` in a bold
///   title stays bold); `<=spec>` replaces it instead.
/// - a tab right-aligns the rest of the line; `{*─}` fills the line with `─`.
pub fn segments(template: &str, v: &Value) -> Vec<Seg> {
    let mut out = Vec::new();
    let mut cur: Option<String> = None;
    let mut rest = template;
    while !rest.is_empty() {
        let Some(i) = rest.find('{') else {
            markup(rest, &mut cur, &mut out);
            break;
        };
        markup(&rest[..i], &mut cur, &mut out);
        if rest[i..].starts_with("{{") {
            push(&mut out, "{", cur.clone(), None);
            rest = &rest[i + 2..];
            continue;
        }
        let Some(j) = rest[i..].find('}') else {
            push(&mut out, &rest[i..], cur.clone(), None);
            break;
        };
        let inner = &rest[i + 1..i + j];
        rest = &rest[i + j + 1..];
        let base = cur.clone();
        if let Some(c) = inner.strip_prefix('*') {
            out.push(Seg { fill: c.chars().next().or(Some(' ')), style: cur.clone(), ..Seg::default() });
            continue;
        }
        let (signed, inner) = match inner.strip_prefix('±') {
            Some(x) => (true, x),
            None => (false, inner),
        };
        let (path, filter) = match inner.split_once('|') {
            Some((p, f)) => (p, Some(f)),
            None => (inner, None),
        };
        let value = scalar(lookup(v, path));
        match filter {
            None => {
                let sign = signed.then(|| number(&value).map(|n| n >= 0.0)).flatten();
                push(&mut out, &value, cur.clone(), sign);
            }
            Some("markup") => markup_in(&value, base.as_deref(), &mut out),
            Some(f) => {
                let picked = if let Some(then) = f.strip_prefix('?') {
                    if value.is_empty() { String::new() } else { then.replace('$', &value) }
                } else if let Some(other) = f.strip_prefix('!') {
                    if value.is_empty() { other.to_string() } else { String::new() }
                } else {
                    let mut hit = None;
                    let mut any = None;
                    for arm in f.split(';') {
                        if let Some((k, x)) = arm.split_once('=') {
                            if k == value {
                                hit = Some(x);
                            } else if k == "*" {
                                any = Some(x);
                            }
                        }
                    }
                    hit.or(any).unwrap_or("").replace('$', &value)
                };
                markup_in(&picked, base.as_deref(), &mut out);
            }
        }
    }
    out.retain(|s| !s.text.is_empty() || s.tab || s.fill.is_some());
    out
}

fn push(out: &mut Vec<Seg>, text: &str, style: Option<String>, sign: Option<bool>) {
    if !text.is_empty() {
        out.push(Seg { text: text.to_string(), style, sign, ..Seg::default() });
    }
}

/// A value's own styles, layered on `base` (the style around the placeholder).
fn markup_in(text: &str, base: Option<&str>, out: &mut Vec<Seg>) {
    let mut cur = base.map(str::to_string);
    markup_with(text, &mut cur, base, out);
}

/// Literal template text: `<spec>` and `</>` switch the style, a tab splits the line.
fn markup(text: &str, cur: &mut Option<String>, out: &mut Vec<Seg>) {
    markup_with(text, cur, None, out);
}

fn markup_with(text: &str, cur: &mut Option<String>, base: Option<&str>, out: &mut Vec<Seg>) {
    let mut rest = text;
    loop {
        let tag = rest.find('<').and_then(|i| {
            let j = rest[i..].find('>')?;
            let spec = &rest[i + 1..i + j];
            let ok = spec == "/" || (!spec.is_empty() && spec.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '+' | '-' | '#' | '_' | '=')));
            ok.then_some((i, j, spec))
        });
        let upto = tag.map(|(i, ..)| i).unwrap_or(rest.len());
        for (k, part) in rest[..upto].split('\t').enumerate() {
            if k > 0 {
                out.push(Seg { tab: true, ..Seg::default() });
            }
            push(out, part, cur.clone(), None);
        }
        let Some((i, j, spec)) = tag else { break };
        *cur = match (spec, base) {
            ("/", _) => base.map(str::to_string),
            (s, _) if s.starts_with('=') => Some(s[1..].to_string()),
            (s, Some(b)) => Some(format!("{b}+{s}")),
            (s, None) => Some(s.to_string()),
        };
        rest = &rest[i + j + 1..];
    }
}

/// Whether a template line shows: it has no placeholders, or at least one fills to something.
/// A line made only of conditional parts that all came out empty is left out, so optional
/// details don't leave gaps.
pub fn shows(template: &str, v: &Value) -> bool {
    let mut any = false;
    let mut rest = template;
    while let Some(i) = rest.find('{') {
        if rest[i..].starts_with("{{") {
            rest = &rest[i + 2..];
            continue;
        }
        let Some(j) = rest[i..].find('}') else { break };
        let ph = &rest[i..i + j + 1];
        rest = &rest[i + j + 1..];
        if ph.starts_with("{*") {
            continue;
        }
        any = true;
        if segments(ph, v).iter().any(|g| !g.text.is_empty()) {
            return true;
        }
    }
    !any
}

/// Only the `{path}` placeholders filled, nothing else read: for markup of other kinds (SVG),
/// where `<g>` is an element, not a style.
pub fn fill_raw(template: &str, v: &Value) -> String {
    let mut out = String::new();
    let mut rest = template;
    while let Some(i) = rest.find('{') {
        out.push_str(&rest[..i]);
        if rest[i..].starts_with("{{") {
            out.push('{');
            rest = &rest[i + 2..];
            continue;
        }
        let Some(j) = rest[i..].find('}') else { break };
        out.push_str(&scalar(lookup(v, &rest[i + 1..i + j])));
        rest = &rest[i + j + 1..];
    }
    out.push_str(rest);
    out
}

/// A template filled as plain text (styles dropped, a tab as `\t`).
pub fn fill(template: &str, v: &Value) -> String {
    segments(template, v)
        .into_iter()
        .map(|s| if s.tab { "\t".to_string() } else { s.text })
        .collect()
}

/// The number in a cell's text: `-1,234.5`, `+4.2%`, `$12k` → -1234.5, 4.2, 12.
pub fn number(s: &str) -> Option<f64> {
    let t: String = s.chars().filter(|c| c.is_ascii_digit() || matches!(c, '-' | '.' | '+')).collect();
    t.parse().ok()
}

/// A dotted path into a value (`items`, `a.b`, `rows.0`); `.` or empty is the value itself.
pub fn lookup<'a>(v: &'a Value, path: &str) -> Option<&'a Value> {
    if path.is_empty() || path == "." {
        return Some(v);
    }
    path.split('.').try_fold(v, |v, k| match v {
        Value::Object(m) => m.get(k),
        Value::Array(a) => k.parse::<usize>().ok().and_then(|i| a.get(i)),
        _ => None,
    })
}

pub fn scalar(v: Option<&Value>) -> String {
    match v {
        None | Some(Value::Null) => String::new(),
        Some(Value::String(s)) => s.clone(),
        Some(Value::Array(a)) => a.iter().map(|x| scalar(Some(x))).collect::<Vec<_>>().join(", "),
        Some(other) => other.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn fill_reads_fields_and_paths() {
        let v = json!({"text": "Buy milk", "due": "2026-10-09", "a": {"b": 3}, "tags": ["x", "y"]});
        assert_eq!(fill("{text} · {due} · {a.b} · {tags} · {nope}", &v), "Buy milk · 2026-10-09 · 3 · x, y · ");
        assert_eq!(fill("{.}", &json!("plain")), "plain");
        assert_eq!(fill("{{literal}", &v), "{literal}");
    }

    #[test]
    fn signed_placeholders_carry_their_sign() {
        let v = json!({"pnl": "-1,204.50", "pct": 3.1});
        let spans: Vec<(String, Option<bool>)> = segments("P&L {±pnl} ({±pct}%)", &v).into_iter().map(|s| (s.text, s.sign)).collect();
        assert_eq!(spans, vec![
            ("P&L ".into(), None), ("-1,204.50".into(), Some(false)), (" (".into(), None),
            ("3.1".into(), Some(true)), ("%)".into(), None)
        ]);
    }

    #[test]
    fn styles_maps_tabs_and_fills() {
        let v = json!({"status": "done", "text": "a <b>bold</b> note", "due": "", "ctx": "Home"});
        let segs = segments("<muted>{status|todo=[ ];done=<done>[x]</>;*=?}</> {text}\t{due|!none}{ctx|? · ¶ $}{*─}", &v);
        let got: Vec<(String, Option<String>, bool, Option<char>)> =
            segs.into_iter().map(|s| (s.text, s.style, s.tab, s.fill)).collect();
        assert_eq!(got, vec![
            // A mapped value's style layers on the one around it.
            ("[x]".into(), Some("muted+done".into()), false, None),
            (" ".into(), None, false, None),
            // Values are plain text: their angle brackets are never styles.
            ("a <b>bold</b> note".into(), None, false, None),
            ("".into(), None, true, None),
            ("none".into(), None, false, None),
            (" · ¶ Home".into(), None, false, None),
            ("".into(), None, false, Some('─')),
        ]);
        assert_eq!(fill("{x|markup}", &json!({"x": "<tag>#a</> b"})), "#a b");
        assert!(shows("static", &v) && shows("{ctx} ", &v) && !shows("<muted>{due|?due $}</> ", &v));
        // Inside a value, styles layer on the surrounding one; `<=…>` replaces it.
        let styles: Vec<Option<String>> = segments("<text+b>{x|markup}</>", &json!({"x": "a <tag>#t</> <=muted>[[</>"}))
            .into_iter().map(|s| s.style).collect();
        assert_eq!(styles, vec![Some("text+b".into()), Some("text+b+tag".into()), Some("text+b".into()), Some("muted".into())]);
    }

    #[test]
    fn a_ui_round_trips_through_json() {
        let ui: Ui = serde_json::from_value(json!({
            "root": {"type": "col", "children": [
                {"type": "text", "text": "hi", "size": 1},
                {"type": "list", "id": "l", "title": "Tasks", "bind": "tasks", "item": "{text}",
                 "keys": {"x": {"run": ["thc", "done", "{id}"]}}}
            ]},
            "data": {"tasks": {"cmd": ["thc", "q", "status:open", "--json"], "path": "items"}},
            "keys": {"q": "quit"}
        }))
        .unwrap();
        let back: Ui = serde_json::from_value(serde_json::to_value(&ui).unwrap()).unwrap();
        assert_eq!(ui, back);
        assert!(ui.root.find("l").unwrap().focusable());
    }
}
